### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by chrisDeFouRire** [Isithelo/Fraternate#8]
Hi there,

I seems like the code for fraternate isn't in this repository at all. When you `npm install fraternate` you get code that's not in this repo at all (like controllers/organisation.js).

And this repository contains a `package.json` that isn't coherent: it's supposed to be for a package named fraternate, yet it includes "fraternate" in its dependencies.

So is the actual source code for fraternate available somewhere? this repo looks more like a template for using fraternate than fraternate itself...

**Comment by jondo89** [comment]
Hi , the intention is to have a standalone fraternate NPM module. However as the website needs its own MVC , this copy of the website (on github ) references the NPM module of the same name. if you want to experiment I would suggest starting with a GitHub clone and stripping from there.

**Comment by jondo89** [comment]
It should be noted that the complexity of the routing between users and orginizations is not completely ironed out .. as such there are a few partials and pages that are required for both. i.e they are not completely stand alone yet.
